### ISSUE TITLE
"SHOP" images should fit in the boxes 

### ISSUE THREAD

**Issue by shnlee0103** [wellns/wellns_web#3]
<img width="724" alt="screen shot 2015-09-11 at 2 21 04 pm" src="https://cloud.githubusercontent.com/assets/14239227/9822793/75b6cd5e-5890-11e5-87c5-74274b3ea27d.png">
<img width="450" alt="screen shot 2015-09-11 at 2 21 13 pm" src="https://cloud.githubusercontent.com/assets/14239227/9822794/75b9812a-5890-11e5-8f5b-4ccaec1d2d44.png">

**Comment by jakelaz** [comment]
Completed- made background-size:contain instead of cover.
