### ISSUE TITLE
Landing page 

### ISSUE THREAD

**Issue by shnlee0103** [wellns/wellns_web#5]
wellness experiences with lower case w

No "wellness coach" under call to action button
should be start browsing for a wellns provider.

<img width="919" alt="screen shot 2015-09-16 at 11 28 24 am" src="https://cloud.githubusercontent.com/assets/14239227/9909411/181f0cfe-5c66-11e5-957c-84baaa0ca520.png">

**Comment by jakelaz** [comment]
Fixed
